apiVersion: apps/v1
kind: Deployment
metadata:
  name: vBUILD_NUMBER
  labels:
    app: vBUILD_NUMBER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vBUILD_NUMBER
  template:
    metadata:
      labels:
        app: vBUILD_NUMBER
    spec:
      containers:
      - name: vBUILD_NUMBER
        image: 374163378991.dkr.ecr.ap-south-1.amazonaws.com/web-app:BUILD_NUMBER
        ports:
        - containerPort: 5000
